apiRules:
- exclude:
    uidRegex: ^Lucene\.Net\.Support\.Character\.\w*SURROGATE
    type: Field
- exclude:
    uidRegex: ^Lucene\.Net\.Test$
    type: Namespace
- exclude:
    uidRegex: ^Lucene\.Net\.RandomExtensions$
    type: Class
